import Foundation

/// A protocol that defines a collection of navigational steps.
///
/// Types conforming to this protocol represent a navigation flow with selectable steps.
/// The protocol provides methods for selecting and checking which step is currently selected.
///
/// ```swift
/// @Steps
/// struct AuthSteps: StepsCollection {
///     var login
///     var register
///     var forgotPassword
/// }
///
/// var steps = AuthSteps.login
/// steps.selected = .register  // Navigate to register screen
/// ```
public protocol StepsCollection {

	/// The type representing all possible steps in the collection.
	///
	/// This type is typically an enum generated by the `@Steps` macro.
	associatedtype AllSteps: Hashable & Codable & Sendable

	/// The currently selected step in the collection.
	///
	/// Setting this property navigates to the selected step.
	var selected: AllSteps { get set }

	/// The ID of the last mutation made to this collection.
	///
	/// This property is used internally for tracking changes to the navigation state.
	var _lastMutateID: MutateID? { get }

	/// Retrieves the step ID for a specific step key path.
	static func step<T>(for keyPath: WritableKeyPath<Self, StepID<T>>) -> AllSteps?

	/// Retrieves the key path for a specific step in the collection.
	static func keyPath(for step: AllSteps) -> PartialKeyPath<Self>?
}

extension StepsCollection {

    /// Checks if a specific step is currently selected.
    ///
    /// - Parameter step: The key path to the step to check.
    /// - Returns: `true` if the specified step is selected, `false` otherwise.
    ///
    /// ```swift
    /// if steps.isSelected(\.login) {
    ///     // We're on the login screen
    /// }
    /// ```
    public func isSelected<T>(_ step: WritableKeyPath<Self, StepID<T>>) -> Bool {
        selected == self[keyPath: step].id
    }

    /// Selects a specific step in the collection.
    ///
    /// - Parameter step: The key path to the step to select.
    ///
    /// ```swift
    /// steps.select(\.register)  // Navigate to the register screen
    /// ```
    public mutating func select<T>(_ step: WritableKeyPath<Self, StepID<T>>) {
        self[keyPath: step].select()
    }

    /// Selects a specific step in the collection and sets its associated value.
    ///
    /// - Parameters:
    ///   - step: The key path to the step to select.
    ///   - value: The value to associate with the selected step.
    ///
    /// ```swift
    /// steps.select(\.profile, with: UserProfile(id: "123"))
    /// ```
    public mutating func select<T>(_ step: WritableKeyPath<Self, StepID<T>>, with value: T) {
        self[keyPath: step].select(with: value)
    }

    /// The full path of selected steps from this collection down to the deepest nested selection.
    ///
    /// Each element is the `selected` value at that nesting level, type-erased to `AnyHashable`.
    /// Always contains at least one element.
    ///
    /// ```swift
    /// var steps: TabSteps = .tab3(.screen2(.text2))
    /// steps.selectedPath // [AnyHashable(.tab3), AnyHashable(.screen2), AnyHashable(.text2)]
    /// ```
    public var selectedPath: [AnyHashable] {
        var path: [AnyHashable] = []
        _collectSelectedPath(into: &path)
        return path
    }

    /// The deepest selected step in the nested hierarchy, type-erased to `AnyHashable`.
    ///
    /// ```swift
    /// var steps: TabSteps = .tab3(.screen2(.text2))
    /// steps.deepSelected // AnyHashable(.text2)
    /// ```
    public var deepSelected: AnyHashable {
        selectedPath.last!
    }

    internal func _collectSelectedPath(into path: inout [AnyHashable]) {
        let sel = selected
        path.append(_unwrapOptionalHashable(sel))
        guard let keyPath = Self.keyPath(for: sel) else { return }
        let value = self[keyPath: keyPath]
        guard let nested = value as? any StepsCollection else { return }
        _collectNestedPath(nested, into: &path)
    }
}

/// Unwraps an optional `Hashable` before converting to `AnyHashable`,
/// so that `Optional<Steps>.some(.screen2)` becomes `AnyHashable(.screen2)` instead of `AnyHashable(Optional.some(.screen2))`.
private func _unwrapOptionalHashable<H: Hashable>(_ value: H) -> AnyHashable {
    if let optional = value as? any _OptionalProtocol {
        return optional._unwrappedAnyHashable ?? value as AnyHashable
    }
    return value as AnyHashable
}

private protocol _OptionalProtocol {
    var _unwrappedAnyHashable: AnyHashable? { get }
}

extension Optional: _OptionalProtocol where Wrapped: Hashable {
    var _unwrappedAnyHashable: AnyHashable? {
        self.map { $0 as AnyHashable }
    }
}

private func _collectNestedPath(_ collection: any StepsCollection, into path: inout [AnyHashable]) {
    collection._collectSelectedPath(into: &path)
}
